# Generated by Django 3.1.7 on 2021-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20210330_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('selected', 'selected'), ('not_selected', 'not_selected'), ('not_verified', 'not_verified')], default='not_verified', max_length=12),
        ),
    ]
