# Generated by Django 3.1.7 on 2021-03-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_auto_20210331_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='desc',
            new_name='price',
        ),
    ]
