# Generated by Django 3.1.7 on 2021-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_auto_20210331_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('email', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('not_booked', 'not_booked'), ('not_booked', 'not_booked')], default='not_verified', max_length=12),
        ),
    ]
