# Generated by Django 3.1.7 on 2021-04-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_auto_20210401_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='rent_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
