# Generated by Django 3.1.7 on 2021-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_info_rent_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rent_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
