# Generated by Django 3.1.7 on 2021-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_booking_rent_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
