# Generated by Django 3.1.7 on 2021-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_info_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(null=True),
        ),
    ]
